spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=Hechizo-servicio
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/(?<segment>.*), /api/${segment}

spring.cloud.gateway.routes[1].id=Hechizo-swagger
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/swagger-ui/**, /api-docs/**, /v3/api-docs/**

logging.level.org.springframework.cloud.gateway=DEBUG
